### ISSUE TITLE
Problem with tests after upgrade to latest version with new exception handling

### ISSUE THREAD

**Issue by NevRA** [konstantinvlasenko/PowerSlim#62]
New exception handling works correct. But we have such strange issue: after few exceptions **EXCEPTION**:ABORT_SLIM_TEST we can't execute tests without slim restart!

To reproduce it copy-paste below script 30 times on fitnesse page and execute it:
!|script|Remote |"slim server name" |
|show |eval |whoami |
|eval |!- throw [System.IO.FileNotFoundException] "File not found !." -!|

When you get **EXCEPTION**:ABORT_SLIM_TEST all next execution on same slim server will fail. First test will fail with ABORT_TEST_INDICATED all next with "Test not run"

**Comment by 2xmax** [comment]
BTW, current implementation test run is yellow (has several exceptions).

**Comment by konstantinvlasenko** [comment]
These exception are by designe as I can see. But agree it is not a good idea to have the yellow tests.
We have the solution for such scenarios check test [http://localhost/PowerSlim.OriginalMode.SuiteExceptions.ExceptionTestRunner](https://github.com/konstantinvlasenko/PowerSlim/blob/master/FitNesseRoot/PowerSlim/OriginalMode/SuiteExceptions/ExceptionTestRunner/content.txt)
