### ISSUE TITLE
Silentlycontinue raises exception

### ISSUE THREAD

**Issue by konstantinvlasenko** [konstantinvlasenko/PowerSlim#72]
@2xmax Tests are Yellow right now after this https://github.com/konstantinvlasenko/PowerSlim/pull/71
Please, check new test case https://github.com/konstantinvlasenko/PowerSlim/commit/632913e02afa0e8d231fb10ba200f89c2f4ac964

**Comment by konstantinvlasenko** [comment]
The behavior of try/catch is to catch terminating errors (exceptions). This means Non-terminating (operational) errors inside a try block will not trigger a Catch. 
**-erroraction silentlycontinue** turns all errors to Non-terminating behavior.
This line https://github.com/konstantinvlasenko/PowerSlim/pull/71/files#diff-3a586a9b299992da7ba63a2496a138f2R259 breaks this approach. @2xmax do you agree?

**Comment by 2xmax** [comment]
That's right, Konstantin. I used -errorVariable switch for such cases in this implementation, that was really very rare (a few cases in large suite). But, I decided to look for a better solution and compared two $error objects such way:
```
$Error.Clear()
New-Item c:\aaa -ItemType directory -ErrorAction SilentlyContinue
$SilentlyContinueErr = $Error[0]

$Error.Clear()
New-Item c:\aaa -ItemType directory #-ErrorAction SilentlyContinue
$UsualErr = $Error[0]

$SilentlyContinueErr | Format-List * -Force
$UsualErr | Format-List * -Force

```

So, one difference I found is writeErrorStream (=True) property
