### ISSUE TITLE
Expression re-execution when a TCP connection is set up

### ISSUE THREAD

**Issue by Alexander-Vakushkin** [konstantinvlasenko/PowerSlim#80]
When a TCP connection is being established to a port on which a slim server is running, that server re-executes its last script. 
If I'm correct, this is due to an unchecked conversion of length field from UTF-8 string to int32 leading to incorrect message buffer clean-up. I made a simple fix for this issue (will post it in a moment).

**Comment by konstantinvlasenko** [comment]
https://github.com/Alexander-Vakushkin/PowerSlim/commit/de2e372ef68e184fc8e93b336f3505b99b996b0e

**Comment by konstantinvlasenko** [comment]
Yes. I noticed this issue as well.
Thank you!
